stages:
  - compile
  - test

build:
  stage: compile
  image: golang:latest
  script:
    - go get -d -v
    - go build -o bin/hexagonalarch -v .

test:
  stage: test
  image: golang:latest
  script:
    - go test services/*.go
